### ISSUE TITLE
inVerse plugin: update to 4.0.6

### ISSUE THREAD

**Issue by akrherz** [igniterealtime/openfire-inverse-plugin#1]
...Migrated from [Ignite Jira OF-1653](https://issues.igniterealtime.org/browse/OF-1653)...

JC released another version of Converse! https://github.com/conversejs/converse.js/releases/tag/v4.0.6

**Comment by wrooot** [comment]
Downloads page still shows 4.0.2 as latest. Also, snapshots downloads are broken.
