### ISSUE TITLE
Update to Converse 5.0.4

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/openfire-inverse-plugin#19]
https://github.com/conversejs/converse.js/releases/tag/v5.0.2
A few security patches among that.

**Comment by wrooot** [comment]
https://github.com/conversejs/converse.js/releases/tag/v5.0.3
5.0.3 already, another security fix

**Comment by guusdk** [comment]
5.0.2 requires that artifacts are served from the `dist` root context (as in: `http://example.org/dist/` ). This is incompatible with Openfire's plugin architecture, that probably needs `inverse/dist` or somesuch. To apply that change to Converse, a new converse build has to be created. I currently can't spare the time to do that.

**Comment by guusdk** [comment]
https://github.com/conversejs/converse.js/releases/tag/v5.0.4
