### ISSUE TITLE
inVerse shows garbled menus with Russian language

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/openfire-inverse-plugin#2]
Tested on 4.3.0 beta, inVerse 4.0.2 Release 1
Same issue fixed for Monitoring plugin https://issues.igniterealtime.org/browse/OF-1500
![image](https://user-images.githubusercontent.com/7195609/50709355-326e9400-1070-11e9-9366-66b4f6f9a98b.png)

**Comment by guusdk** [comment]
I believe that this issue is already fixed in https://github.com/igniterealtime/Openfire/pull/1174

Using the latest snapshot (4.1.0-SNAPSHOT) that was created earlier today, things look good to me.

**Comment by wrooot** [comment]
Fixed in 4.1.0.1
