### ISSUE TITLE
Issues with inVerse downloads

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/openfire-inverse-plugin#4]
Downloads page still shows 4.0.2 as latest. Also, snapshots downloads are broken.

_Originally posted by @wrooot in https://github.com/igniterealtime/openfire-inverse-plugin/issue_comments#issuecomment-451944293_

**Comment by guusdk** [comment]
@GregDThomas - the version of this plugin has a weird format, that appears to clash with the new SNAPSHOT/timestamp detection code introduced in https://github.com/igniterealtime/IgniteRealtime-Website/commit/163f7ac69ece9de16014848c5c25b89f88d4031d. Do you have time to have a look?

**Comment by GregDThomas** [comment]
Looking now ...

**Comment by GregDThomas** [comment]
I think https://github.com/igniterealtime/IgniteRealtime-Website/pull/92 fixes it

**Comment by wrooot** [comment]
Yep, snapshots are fixed now. But what about the latest release? 4.0.2 is old one.

**Comment by wrooot** [comment]
I'm referring this PR https://github.com/igniterealtime/openfire-inverse-plugin/pull/3 which is merged, so i figured new version of plugin should be released (or maybe not, and it is waiting for more changes). There is 4.0.4 snapshot of inVerse, but no official release. Maybe Guus hasn't copied it to Archiva (4.0.4 snapshot is there).

**Comment by GregDThomas** [comment]
Unfortunately this is another case where the version in the pom.xml (`4.0.6-release-1-SNAPSHOT`) doesn't match the plugin.xml (`4.0.6 Release 1`). It's the version in the pom.xml that decides the release status.

**Comment by wrooot** [comment]
I wasn't sure if Converse version should always match inVerse. But maybe you are right and it should be 4.0.6 instead. I wonder what is the release process then or is Guus waiting for more changes to include before releasing 4.0.6.

**Comment by guusdk** [comment]
Proposed fix in https://github.com/igniterealtime/openfire-inverse-plugin/pull/5
